/** Declaration file generated by dts-gen */

export class BasicClient {
  constructor(...args: any[]);

  createDelete(...args: any[]): void;

  createGet(...args: any[]): void;

  createGetBlob(...args: any[]): void;

  createPost(...args: any[]): void;

  createPostBlob(...args: any[]): void;

  createPostFile(...args: any[]): void;

  createPostForm(...args: any[]): void;

  createPostJSON(...args: any[]): void;

  createPut(...args: any[]): void;

  createPutBody(...args: any[]): void;

  createPutJSON(...args: any[]): void;
}

export const service_providers: {
  account_web_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  agency_web_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  common: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  crm_customer: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  crm_order_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  crm_pool: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  finance_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  ims: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  invoice_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  market: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  message_center_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  our_v1: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  our_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  partner_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  product_center_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  product_center_v2_special: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  product_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  queqiao_platform: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  queqiao_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  report_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  rys_coupon: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  serverless_package_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  serverless_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  tax_console: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  tenant_console: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  tenant_console_v2: {
    client: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: any;
    };
    legacyRawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
    rawClient: {
      createDelete: any;
      createGet: any;
      createGetBlob: any;
      createPost: any;
      createPostBlob: any;
      createPostFile: any;
      createPostForm: any;
      createPostJSON: any;
      createPut: any;
      createPutBody: any;
      createPutJSON: any;
      httpClient: any;
      isRaw: boolean;
    };
  };
  user_auth: {
    createDelete: any;
    createGet: any;
    createGetBlob: any;
    createPost: any;
    createPostBlob: any;
    createPostFile: any;
    createPostForm: any;
    createPostJSON: any;
    createPut: any;
    createPutBody: any;
    createPutJSON: any;
    httpClient: any;
    isRaw: any;
  };
  user_auth_wild: {
    createDelete: any;
    createGet: any;
    createGetBlob: any;
    createPost: any;
    createPostBlob: any;
    createPostFile: any;
    createPostForm: any;
    createPostJSON: any;
    createPut: any;
    createPutBody: any;
    createPutJSON: any;
    httpClient: any;
    isRaw: any;
  };
  user_center: {
    createDelete: any;
    createGet: any;
    createGetBlob: any;
    createPost: any;
    createPostBlob: any;
    createPostFile: any;
    createPostForm: any;
    createPostJSON: any;
    createPut: any;
    createPutBody: any;
    createPutJSON: any;
    httpClient: any;
    isRaw: any;
  };
};

export const utils: {
  saas: {
    generateClients: any;
  };
};

export function RysClient(...args: any[]): void;

export function SaasClient(...args: any[]): void;

export function setAdapter(...args: any[]): void;

export namespace RysClient {
  const mw_slots_manager: {
    req_pre: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    req_sub: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    res_pre: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    res_sub: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
  };

  function createClient(service: any, request_mws: any, response_mws: any): any;

  function createRawClient(
    service: any,
    request_mws: any,
    response_mws: any
  ): any;
}

export namespace SaasClient {
  const mw_slots_manager: {
    req_pre: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    req_sub: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    res_pre: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    res_sub: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
  };

  const mw_slots_manager_legacy: {
    req_pre: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    req_sub: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    res_pre: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
    res_sub: {
      concat: any;
      fullfilled: any;
      mws: any[];
      rejected: any;
      set: any;
    };
  };
}

export namespace client {
  const isRaw: any;

  function createDelete(...args: any[]): void;

  function createGet(...args: any[]): void;

  function createGetBlob(...args: any[]): void;

  function createPost(...args: any[]): void;

  function createPostBlob(...args: any[]): void;

  function createPostFile(...args: any[]): void;

  function createPostForm(...args: any[]): void;

  function createPostJSON(...args: any[]): void;

  function createPut(...args: any[]): void;

  function createPutBody(...args: any[]): void;

  function createPutJSON(...args: any[]): void;

  function httpClient(...args: any[]): any;

  namespace httpClient {
    const interceptors: {
      request: {
        eject: any;
        forEach: any;
        handlers: {
          fulfilled: any;
          rejected: any;
        }[];
        use: any;
      };
      response: {
        eject: any;
        forEach: any;
        handlers: {
          fulfilled: any;
          rejected: any;
        }[];
        use: any;
      };
    };

    function get(...args: any[]): any;

    function getUri(...args: any[]): any;

    function head(...args: any[]): any;

    function options(...args: any[]): any;

    function patch(...args: any[]): any;

    function post(...args: any[]): any;

    function put(...args: any[]): any;

    function request(...args: any[]): any;

    namespace defaults {
      const baseURL: string;

      const headers: {
        "Content-Type": string;
        common: {
          Accept: string;
        };
        delete: {};
        get: {};
        head: {};
        patch: {
          "Content-Type": string;
        };
        post: {
          "Content-Type": string;
        };
        put: {
          "Content-Type": string;
        };
      };

      const maxBodyLength: number;

      const maxContentLength: number;

      const timeout: number;

      const transformRequest: any[];

      const transformResponse: any[];

      const xsrfCookieName: string;

      const xsrfHeaderName: string;

      function adapter(config: any): any;

      function validateStatus(status: any): any;
    }
  }
}

export namespace rawClient {
  const isRaw: boolean;

  function createDelete(...args: any[]): void;

  function createGet(...args: any[]): void;

  function createGetBlob(...args: any[]): void;

  function createPost(...args: any[]): void;

  function createPostBlob(...args: any[]): void;

  function createPostFile(...args: any[]): void;

  function createPostForm(...args: any[]): void;

  function createPostJSON(...args: any[]): void;

  function createPut(...args: any[]): void;

  function createPutBody(...args: any[]): void;

  function createPutJSON(...args: any[]): void;

  function httpClient(...args: any[]): any;

  namespace httpClient {
    const interceptors: {
      request: {
        eject: any;
        forEach: any;
        handlers: {
          fulfilled: any;
          rejected: any;
        }[];
        use: any;
      };
      response: {
        eject: any;
        forEach: any;
        handlers: {
          fulfilled: any;
          rejected: any;
        }[];
        use: any;
      };
    };

    function get(...args: any[]): any;

    function getUri(...args: any[]): any;

    function head(...args: any[]): any;

    function options(...args: any[]): any;

    function patch(...args: any[]): any;

    function post(...args: any[]): any;

    function put(...args: any[]): any;

    function request(...args: any[]): any;

    namespace defaults {
      const headers: {
        "Content-Type": string;
        common: {
          Accept: string;
        };
        delete: {};
        get: {};
        head: {};
        patch: {
          "Content-Type": string;
        };
        post: {
          "Content-Type": string;
        };
        put: {
          "Content-Type": string;
        };
      };

      const maxBodyLength: number;

      const maxContentLength: number;

      const timeout: number;

      const transformRequest: any[];

      const transformResponse: any[];

      const xsrfCookieName: string;

      const xsrfHeaderName: string;

      function adapter(config: any): any;

      function validateStatus(status: any): any;
    }
  }
}
